// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA53xtuewcPizG4cl7epg_CE57B00wOMig',
    appId: '1:432624716433:web:66b5ca46d9f8ff9a56cd30',
    messagingSenderId: '432624716433',
    projectId: 'fitfuel-a1fb5',
    authDomain: 'fitfuel-a1fb5.firebaseapp.com',
    storageBucket: 'fitfuel-a1fb5.firebasestorage.app',
    measurementId: 'G-1JRX2MRE8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZqn-jLA994IIN3o9BNgPP4BAqNGmZy8',
    appId: '1:432624716433:android:037dbd193825ab4056cd30',
    messagingSenderId: '432624716433',
    projectId: 'fitfuel-a1fb5',
    storageBucket: 'fitfuel-a1fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kf1ZOsLzka7R-9kZHqiRLHcwbQ9Ed90',
    appId: '1:432624716433:ios:957b7f5b1396838856cd30',
    messagingSenderId: '432624716433',
    projectId: 'fitfuel-a1fb5',
    storageBucket: 'fitfuel-a1fb5.firebasestorage.app',
    iosBundleId: 'com.example.fitfuel',
  );
}
